"""add products table

Revision ID: b772ec45c3ac
Revises: 9ea6d612d4b9
Create Date: 2023-07-07 20:45:06.200806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b772ec45c3ac'
down_revision = '9ea6d612d4b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
